language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install unittest
  
# command to run tests
script:
  - unittest discover -p 'test_*.py'
